export { default as Table } from './Table'
export { default as TableBody } from './TableBody'
export { default as TableData } from './TableData'
export { default as TableHead } from './TableHead'
export { default as TableHeading } from './TableHeading'
export { default as TableRow } from './TableRow'
