import PropTypes from 'prop-types'
import React from 'react'

const Box = ({
  sm,
  md,
  lg,
  xl,
  padding,
  paddingLeft,
  paddingRight,
  paddingTop,
  paddingBottom,
  margin,
  marginLeft,
  marginRight,
  marginTop,
  marginBottom,
  children
}) => (
  <div
    className={`w-${sm} sm:w-${sm} md:w-${md} lg:w-${lg} xl:w-${xl} p-${padding} pl-${paddingLeft} pr-${paddingRight} pt-${paddingTop} pb-${paddingBottom} m-${margin} ml-${marginLeft} mr-${marginRight} mt-${marginTop} mb-${marginBottom}`}
  >
    {children}
  </div>
)

Box.defaultProps = {
  sm: 'full',
  padding: '0',
  margin: '0'
}

Box.propTypes = {
  sm: PropTypes.oneOf([
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '8',
    '10',
    '12',
    '16',
    '24',
    '32',
    '48',
    '64',
    'auto',
    'px',
    '1/2',
    '1/3',
    '1/4',
    '3/4',
    '1/5',
    '2/5',
    '3/5',
    '4/5',
    '1/6',
    '5/6',
    'full',
    'screen'
  ]),
  md: PropTypes.oneOf([
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '8',
    '10',
    '12',
    '16',
    '24',
    '32',
    '48',
    '64',
    'auto',
    'px',
    '1/2',
    '1/3',
    '1/4',
    '3/4',
    '1/5',
    '2/5',
    '3/5',
    '4/5',
    '1/6',
    '5/6',
    'full',
    'screen'
  ]),
  lg: PropTypes.oneOf([
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '8',
    '10',
    '12',
    '16',
    '24',
    '32',
    '48',
    '64',
    'auto',
    'px',
    '1/2',
    '1/3',
    '1/4',
    '3/4',
    '1/5',
    '2/5',
    '3/5',
    '4/5',
    '1/6',
    '5/6',
    'full',
    'screen'
  ]),
  xl: PropTypes.oneOf([
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '8',
    '10',
    '12',
    '16',
    '24',
    '32',
    '48',
    '64',
    'auto',
    'px',
    '1/2',
    '1/3',
    '1/4',
    '3/4',
    '1/5',
    '2/5',
    '3/5',
    '4/5',
    '1/6',
    '5/6',
    'full',
    'screen'
  ]),
  padding: PropTypes.oneOf(['0', '1', '2', '3', '4', '5', '6', '7', '8']),
  paddingLeft: PropTypes.oneOf(['0', '1', '2', '3', '4', '5', '6', '7', '8']),
  paddingRight: PropTypes.oneOf(['0', '1', '2', '3', '4', '5', '6', '7', '8']),
  paddingTop: PropTypes.oneOf(['0', '1', '2', '3', '4', '5', '6', '7', '8']),
  paddingBottom: PropTypes.oneOf(['0', '1', '2', '3', '4', '5', '6', '7', '8']),
  margin: PropTypes.oneOf(['0', '1', '2', '3', '4', '5', '6', '7', '8']),
  marginLeft: PropTypes.oneOf(['0', '1', '2', '3', '4', '5', '6', '7', '8']),
  marginRight: PropTypes.oneOf(['0', '1', '2', '3', '4', '5', '6', '7', '8']),
  marginTop: PropTypes.oneOf(['0', '1', '2', '3', '4', '5', '6', '7', '8']),
  marginBottom: PropTypes.oneOf(['0', '1', '2', '3', '4', '5', '6', '7', '8']),
  children: PropTypes.node.isRequired
}

export default Box
